name: Run tests

on:
  push:
    branches:
      - '*'       # matches every branch that doesn't contain a '/'
      - '*/*'     # matches every branch containing a single '/'
      - '**'      # matches every branch
      - '!master' # excludes `master` branch

env:
  CGO_ENABLED: 0 # Build statically linked binaries

jobs:
  fmt_and_vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Check vet
        run: |
          go vet ./...

      - name: Check fmt
        run: |
          go fmt ./...
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "Formatting is consistent with 'go fmt'."
          else
            echo "Run 'go fmt ./...' to automatically apply standard Go style to all packages."
            git status --porcelain
            exit 1
          fi

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        go_version: ['1.25']
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build code
        run: go build -v ./...

      - name: Running unit tests
        run: |
          go test -v ./...
